FROM python:3.11-slim

# ОБЯЗАТЕЛЬНО!
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# ОБЯЗАТЕЛЬНО запускать из bot/ внутри /app
CMD ["python", "bot/bot.py"]
