FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Для миграций нам достаточно psycopg2 и dotenv
RUN pip install --no-cache-dir psycopg2-binary python-dotenv

COPY . /app

CMD ["python", "database/init_db.py"]
