FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# ВАЖНО: запуск через модуль, чтобы пакет bot корректно резолвился
CMD ["python", "-m", "bot.bot"]
